### ISSUE TITLE
Runtime Invisible Annotations

### ISSUE THREAD

**Issue by MikeEdgar** [wildfly/jandex#120]
We had an issue a few weeks back smallrye/smallrye-open-api#716 requesting information to be utilized from a `@Retention(RetentionPolicy.CLASS)` annotation.  I'm curious if there is any interest in having runtime invisible annotations present in an index. I suppose the original reason for leaving them out was to more closely match reflection APIs, correct? Is this something that could be a candidate for version 3?

**Comment by Ladicek** [comment]
Done in #129.
