### ISSUE TITLE
Move to Java 8 as minimum

### ISSUE THREAD

**Issue by Ladicek** [wildfly/jandex#123]

**Comment by gastaldi** [comment]
Why not Java 11 as a minimum already?

**Comment by Ladicek** [comment]
There are Jandex consumers that are still on 8. Plus, we can stay on 8 (heck, we could stay on 6, but let's not) and support latest Java bytecode just fine. Jandex 2.4.0.Final will support records, for example :-)

**Comment by Ladicek** [comment]
This was done together with #122 on the `smallrye` branch, no need to leave this open.
