### ISSUE TITLE
Class signature parsing skipped for records

### ISSUE THREAD

**Issue by MikeEdgar** [wildfly/jandex#160]
The `Indexer#applySignatures` method requires that the signature for a class be the last entry in the list of signatures. However, with records, the class's signature is followed by the record components' signatures. 

An example record that where generic type information is not included in the index for the class's type parameters.
```java
record MyRecord<T>(T content) {
} 
```

**Comment by Ladicek** [comment]
That's probably because record components are stored in class attributes and hence are parsed later on. Still, should be straightforward to fix. If you don't get to it, I should in the next few days.

**Comment by MikeEdgar** [comment]
> That's probably because record components are stored in class attributes and hence are parsed later on.

Yep, exactly. I have a local fix that I've tested locally that I will push to a PR today.

**Comment by Ladicek** [comment]
Perfect, thank you!
