### ISSUE TITLE
[Question] Index "jrt-fs.jar"

### ISSUE THREAD

**Issue by BoykoAlex** [wildfly/jandex#42]
Can you propose a way to index "jrt-fs.jar" please?
Or maybe have a `JarFsIndexer`?

**Comment by n1hility** [comment]
@BoykoAlex sorry I didn't see this issue (I have been using JIRA to track issues), however considering switching to GitHub for everything.

Can you expand on this a bit more? You can generate an index of jrt-fs.jar, or do you mean indexing the content of module images?

**Comment by BoykoAlex** [comment]
I meant indexing the content of `jrt-fs.jar`, but think it's ok I got to the stuff (modules and .lcass files) inside of `jrt-fs.jar` and indexed with Jandex :-)
