### ISSUE TITLE
Support a reliable way to get a parameter type

### ISSUE THREAD

**Issue by gsmet** [wildfly/jandex#45]
Currently, to get the parameter type, we need to do something like:
```
methodParameterInfo.method().parameters().get(methodParameterInfo.position())
```

The issue with this is that `parameters()` includes the synthetic parameters (confirmed by @FroMage ) whereas they are not counted in the result of `position()`, leading to incorrect results if we have synthetic parameters.

@FroMage implemented a nice user friendly API to get the parameter name. We should do the same for the parameter type.

**Comment by FroMage** [comment]
For backwards compat I can't change the behaviour of `parameters()`, but I can find another solution.

**Comment by FroMage** [comment]
Well, actually, parameter annotations will tell us the number of non-synthetic params. Parameter names (if present in the bytecode) will also tell us. But if you method has no annotation and no parameter name it has no info on synthetic params. And also, javac and ECJ generate different synthetic params for enums. So it's not that easy.

**Comment by FroMage** [comment]
```java
    /**
     * Returns the nesting type of this class, which could either be a standard top level class, an inner class,
     * an anonymous class, or a local class.
     *
     * <p>For historical reasons, static nested classes are returned as <code>INNER</code>. You can differentiate
     * between a non-static nested class (inner class) and a static nested class by calling
     * {@link java.lang.reflect.Modifier#isStatic(int)} on the return of {@link #flags()} </p>
     *
     * @return the nesting type of this class
     */
    public NestingType nestingType() {
...
```

This is lying at least with ECJ, the `ACC_STATIC` flag is missing in the bytecode.

**Comment by FroMage** [comment]
Actually it works and `javap` is just hiding it.

**Comment by FroMage** [comment]
OK, so:

- I can get it to work for toplevel and inner classes. 
- For local classes it requires an `Index` parameter to look up the declaring method's class to see if it's static. 
- For anonymous classes it doesn't look like Jandex actually supports them (I can't find any instance of an anonymous class that responds anything else than TOPLEVEL).
- For enums I can't figure out how to make it work. ECJ produces the following bytecode:

```
  private org.jboss.jandex.test.BasicTestCase$Enum(java.lang.String, int, byte);
    descriptor: (Ljava/lang/String;IB)V
```

Where the `String, int` are synthetic and the byte is real, but javac produces this:

```
  private org.jboss.jandex.test.BasicTestCase$Enum(byte);
    descriptor: (Ljava/lang/String;IB)V
```

Notice that the signatures are different, and jandex does respect the signature when you look up the method, but the descriptor contains additional parameters. So I can't actually support this by looking at the bytecode.

**Comment by FroMage** [comment]
Lets rewind a bit @gsmet: we only get synthetic params for constructors of non-static inner classes (including local/anon) and enums. Is there any use-case where you would actually look at the type of those constructors's params? In most usages I would ignore those because you can't easily invoke them. But perhaps your use-case is different?

**Comment by gsmet** [comment]
Enums shouldn't be an issue for sure. My concern was more about non-static inner classes and constructor validation.

But I suppose for now, we can ignore this. It was more to be thorough and avoid unexpected array out of bound exceptions.

**Comment by FroMage** [comment]
So what are you going to do with those non-static inner classses?

**Comment by FroMage** [comment]
Is #48 OK for you?

**Comment by n1hility** [comment]
> * For anonymous classes it doesn't look like Jandex actually supports them (I can't find any instance of an anonymous class that responds anything else than TOPLEVEL).

Are you sure that's the case? That's the whole reason the value exists?

**Comment by n1hility** [comment]
I added some tests for nesting type which appear to work: 
https://github.com/wildfly/jandex/commit/a8b6a213de7c19915018a941c408c370e07be2f2

**Comment by n1hility** [comment]
> * For local classes it requires an `Index` parameter to look up the declaring method's class to see if it's static.

This shouldn't be needed, a local class can't be static.

**Comment by n1hility** [comment]
So I think what needs to research this a little more. My current thinking is that everything the class file spec references the real absolute descriptor positions (so including synthetic) and its only the generic info which does not have synthetic data. So we should check the annotation attribute values to verify that understanding. I'm 99.9999% positive its at least the case with LocalVariableTable, since the descriptor is how the JVM operates with opcodes. Assuming that is the case the we need to be more intelligent about the applySignature step in the indexing process. If we have parameter name info we can easily merge that by skipping over the synthetic params. If we don't we are SOL and probably have to drop the generic info if there is a count mismatch.

**Comment by n1hility** [comment]
Looking at the javap output parameter annotations does indeed correspond with signature (no synethic info) LocalVariable table has slots that correspond with real parameters (as expected), synthetic params are committed.

**Comment by FroMage** [comment]
> Are you sure that's the case? That's the whole reason the value exists?

Damn, I have to recheck then.

**Comment by FroMage** [comment]
> This shouldn't be needed, a local class can't be static.

They can, if they are in a static block or method, which depends on the enclosing method.

**Comment by FroMage** [comment]
> Ok so after thinking about this for awhile I am starting to think that synthetic parameters have zero value and we should just exclude them

On the one hand I agree, they have no value. On the other they are also a good indicator that you won't be able to use reflection to call the annotated method/constructor if they are there. The easiest case is an inner type which requires the outer instance, but you still have to get it. All other cases, such as enums, anonymous types or local types, it's hard to conceive of a reason to instantiate them, let alone get all the required synthetic values to satisfy the synthetic params. 

Given that most use-cases I've seen so far of indexing methods are about collecting info about the method, but ultimately to be able to invoke it, I think all these cases are degenerate and non-useful for indexing. So perhaps not worth spending too much time on?

Examples of synthetic params that I've come across:

- non-static types: pointer to the outer instance, always as the first param
- enums: in some cases, `String` and `int`
- local types: any final captured variable value (can combine with the outer instance too), almost always _after_ real params

**Comment by FroMage** [comment]
@n1hility so here's my test which fails for anonymous types: https://github.com/wildfly/jandex/commit/995766435d73f26f3a8961a0c2a831c2863f3596

I'm testing anonymous types inside static init and normal init blocks. Perhaps that's the only cases where it fails? I did plan on testing inside constructors and then static/normal methods after that.

**Comment by n1hility** [comment]
@FroMage ah yep, that's a bug, fix is in 6da4d88db0389f19bf2cacdc84335c886c230b89

**Comment by n1hility** [comment]
@FroMage ok the invocation case is convincing but for sure we can't correlate the signature with the true descriptor UNLESS method parameter info is included  (LocalVariableTable could probably also work using the slot info). If we can't correlate we will have to store two parameter arrays, and also return some sort of sentinel in APIs that no longer works (for example when looking up an annotation targeted to a MethodParameterInfo it would return -1 for descriptorPos). Unfortunately alot of code will fall into the scenario. Luckily synthetic parameters are uncommon, so we only need the two arrays when we don't have info and the descriptor length doesn't match the signature length.

**Comment by n1hility** [comment]
@FroMage @gsmet I have started to address this with type annotations related to other fixes/improvements. In the type annotation case there was virtually no compatibility impact, so this was already applied in the latest bug fix release. However, I suspect calling code exists for standard parameter annotations that does deal with adjusting the position, so I am thinking behavioral changes relating to this need to be done in the next minor at least. 

The changes I plan to make is to auto adjust annotation parameter indexes for non-static inner classes (local, anon, and nested). In this way you can reliably use the index.

For enums I need to do a little more research.

**Comment by Ladicek** [comment]
Done in #192.
