### ISSUE TITLE
Not a parameterized type! exception during indexing a class

### ISSUE THREAD

**Issue by tosix1988** [wildfly/jandex#55]
I have found this error in the Wildfly server logs while deploying my application. Finally, I was able to create a simple test that reproduces this issue. Note that I use Lombok in my project, so it is likely that this is not an issue of Jandex per se, but it might be a problem of Lombok code generation, or some other problem.

To demonstrate, let's assume we have the following class:
```java
@AllArgsConstructor(access = AccessLevel.PACKAGE)
public class SampleEntity {
	private Set<@TypeAnnotation String> userRoles;

	public Set<String> getUserRoles() {
		return userRoles;
	}
}
```
where the `@TypeAnnotation` is just an empty annotation. The test project is avaliable here: [jandex-sample-project.zip](https://github.com/wildfly/jandex/files/3034868/jandex-sample-project.zip). A simple test I have created just tries to index this class by Jandex.

When running `mvn clean verify`, the following exception occurs:
```
java.lang.IllegalArgumentException: Not a parameterized type!
        at org.jboss.jandex.Type.asParameterizedType(Type.java:228)
        at org.jboss.jandex.Indexer.resolveTypePath(Indexer.java:767)
        at org.jboss.jandex.Indexer.resolveTypeAnnotation(Indexer.java:727)
        at org.jboss.jandex.Indexer.resolveTypeAnnotations(Indexer.java:612)
        at org.jboss.jandex.Indexer.index(Indexer.java:1604)
        at sk.tosix.sample.IndexerTest.test(IndexerTest.java:17)
```

I have played a bit with this, and it seems that the following causes the error to disappear:

 - I have let Lombok to delombok the source of this Lombok-annotated class; Jandexing the generated class goes without issues.
 - Removing the `@TypeAnnotation` from the userRoles declaration makes the error disappear.
 - Removing the `@AllArgsConstructor` annotation and creating the constructor by hand (basically the same as delomboking the class) makes the error disappear.
 - opening this project in Eclipse and compiling it there (not by javac, but by ecj) makes the error disappear.

It is possible that it is Lombok to blame here, but as I am no expert in bytecode interpretation and as it is Jandex that throws the error, I am asking you guys for help :)

**Comment by chonton** [comment]
I think this is a lombok issue.  See https://github.com/rzwitserloot/lombok/issues/2189
