### ISSUE TITLE
Indexer option to control ClassInfo sorting

### ISSUE THREAD

**Issue by neon-dev** [wildfly/jandex#58]
[SmallRye's OpenAPI implementation](https://github.com/smallrye/smallrye-open-api/) uses Jandex. Not only for annotation processing but also to get general reflective class info. Unfortunately object fields are sorted by Jandex: https://github.com/wildfly/jandex/blob/61d1115e0a0f15dcfb2b0bbd082100f847963529/src/main/java/org/jboss/jandex/ClassInfo.java#L557
This ultimately alters the field order of all objects appearing in the openapi file, though in most cases declaration order is desired.

It would therefore be great to have an [Indexer](https://github.com/wildfly/jandex/blob/master/src/main/java/org/jboss/jandex/Indexer.java) option to configure ClassInfo's field sorting behavior. Maybe for completeness also for [methods](https://github.com/wildfly/jandex/blob/61d1115e0a0f15dcfb2b0bbd082100f847963529/src/main/java/org/jboss/jandex/ClassInfo.java#L581).

Thanks!

**Comment by neon-dev** [comment]
@n1hility any update about this topic? If it's out of scope (even though a simple flag :smirk:) it would be nice to know. In that case the linked issue will be more complex to fix, but at least we have clarity about it.

**Comment by vlsi** [comment]
@neon-dev , can you please clarify what do you mean by "declaration order"?
Java specification has no guarantees that the fields and methods will appear in exactly the same order in the bytecode.
Then, `Class#getMethods` has the following javadoc:

>The elements in the returned array are not sorted and are not in any particular order.

Sorting entries might help build reproducibility (see https://reproducible-builds.org/ ).
Then "storing original method positions" would make "index merging" slightly harder.

**Comment by neon-dev** [comment]
@vlsi correct, but in practice I've not yet seen the compiler shift methods and fields around. So it'd be great to have a way to tell Jandex to retain the original/input order, even if it may not be consistent over different bytecode versions. Meaning whatever `getDeclaredMethods` and `getDeclaredFields` returns, take it as is.
