### ISSUE TITLE
Support JEP 309: Dynamic Class-File Constants (introduced in JDK 11)

### ISSUE THREAD

**Issue by gastaldi** [wildfly/jandex#68]
Current code throws: 
```
java.lang.IllegalStateException: Unknown tag! pos=156 poolCount = 174
	at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:1563)
	at org.jboss.jandex.Indexer.index(Indexer.java:1597)
```

This is the output of `javap -v <classfile>`
```
  #157 = Dynamic            #1:#156       // #1:$jacocoData:Ljava/lang/Object;
```

**Comment by dmlloyd** [comment]
From chat:

> Jason Greene 15:04
> @*David Lloyd* yeah just ignoring is really the only option unless you emulate a vm and execute the bootstrap method. i think that should be ok since I think that these cant be referenced from static program structures (method signatures, annotation defaults etc)

**Comment by gastaldi** [comment]
I'm working on it. I'll provide a PR with tests
