### ISSUE TITLE
org.jboss.jandex.AnnotationValue.BooleanValue does not override equals()/hashCode()

### ISSUE THREAD

**Issue by mkouba** [wildfly/jandex#81]
As a result, the boolean values is ignored in `equals()`, i.e. it returns always `true` for two boolean annotation values with the same name.

**Comment by famod** [comment]
I am asking myself why `AnnotationValue.equals()` isn't just using `value()`. It could then also be made `final`.
Another approach would be to make `toString()` abstract, _forcing_ all subclasses to implement it.
