### ISSUE TITLE
RFE: Add method ClassInfo.toClass() for Quarkus (API gap)

### ISSUE THREAD

**Issue by ge0ffrey** [wildfly/jandex#89]
As discussed here with Stuart and Guillaume:
https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Convert.20Jandex.20ClassInfo.20to.20Class
quarkus extensions often have to convert a Jandex ClassInfo into a Class, which Jandex doesn't support (it's an API gap).

Now, converting it into a Class, does mean the Class gets instantiated, which means the user must be well aware of the cost of that side effect, but that seems obvious to me - otherwise ClassInfo would not exist.

The code itself:

```
public <T> Class<T> toClass() {
        String className = name().toString();
       ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
        try {
            return (Class<T>) classLoader.loadClass(className);
        } catch (ClassNotFoundException e) {
            throw new IllegalStateException("The class (" + className
                    + ") cannot be created.", e);
        }
}
```

**Comment by Ladicek** [comment]
I recently added something similar in Quarkus: https://github.com/quarkusio/quarkus/blob/47476df7066fb58f1eb1853845cc4982184e267d/core/deployment/src/main/java/io/quarkus/deployment/util/JandexUtil.java#L380-L430

Adding it to Jandex makes sense to me, but I would definitely not put it into `ClassInfo` or `Type`. An extra util method like `JandexReflection.loadClass` should work fine and clearly shows that there's price to pay.

**Comment by Ladicek** [comment]
Done in #200.
