### ISSUE TITLE
Indexer vs DotName.equals() for a nested class with simple name that ends with $

### ISSUE THREAD

**Issue by mkouba** [wildfly/jandex#97]
If there is a nested class with simple name `Test$`, e.g. `org.jboss.jandex.test.IndexerTestCase$Test$` (note that although it's not recommended it's legal to use `$` in a class name) then `Indexer` decodes the `DotName` as:
```
componentized	true	
innerClass	true	
local	"" (id=108)	
prefix	DotName  (id=111)	
   componentized	true	
   innerClass	true	
   local	"Test" (id=117)
   prefix	DotName  (id=86)	
      componentized	true	
      innerClass	false	
      local	"test" (id=130)	
      prefix	DotName  (id=131)	
         ...
```
The `toString()` of the `DotName` is `org.jboss.jandex.test.IndexerTestCase$Test$` however the `equals()` method does not match the following:
```java
DotName org = DotName.createComponentized(null, "org");
DotName jboss = DotName.createComponentized(org, "jboss");
DotName jandex = DotName.createComponentized(jboss, "jandex");
DotName test = DotName.createComponentized(jandex, "test");
DotName indexerTestCase = DotName.createComponentized(test, "IndexerTestCase");
DotName testName = DotName.createComponentized(indexerTestCase, Test$.class.getSimpleName(), true);
```
whose `toString()` is also `org.jboss.jandex.test.IndexerTestCase$Test$`.

Maybe I'm missing something obvious.

**Comment by mkouba** [comment]
CC @Sanne @n1hility

**Comment by mkouba** [comment]
A test case is available in my branch: https://github.com/mkouba/jandex/tree/issue-97

**Comment by n1hility** [comment]
thanks will check it out

**Comment by ungerts** [comment]
At least the test execution is now successful.

**Comment by ungerts** [comment]
I think a general solution should take into account the [InnerClasses Attribute](https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-4.7.6) of the class file and iterate through the [outer classes which are already parsed](https://github.com/wildfly/jandex/blob/master/src/main/java/org/jboss/jandex/Indexer.java#L408).

**Comment by Ladicek** [comment]
I'm looking at the idea of using the `InnerClasses` attribute and while I agree it would be the best way to do it, I also believe doing that would require a major overhaul of the indexing algorithm. The `ClassFile` attributes are stored at the very end of the class file, and we [currently] [have to] parse names way before reaching that point. So it's currently not practical, unfortunately.
